local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local d = ls.dynamic_node
local rep = require("luasnip.extras").rep

local rec_ls
rec_ls = function()
	return sn(
		nil,
		c(1, {
			t(""),
			sn(nil, { t({ "", "\t\\item " }), i(1), d(2, rec_ls, {}) }),
		})
	)
end

return({
  s({ trig = 'beamer', name = 'LaTeX beamer UoS theme' }, {
    t({
      '\\documentclass{beamer}',
      '\\geometry{paperwidth=170.67mm, paperheight=96mm}',
      '\\setbeamertemplate{navigation symbols}{}',
      '\\mode<presentation>',
      '{',
      '\t\\usetheme{Madrid}',
      '\t\\definecolor{uos-signature-blue}{RGB}{10,77,155}',
      '\t\\colorlet{beamer@blendedblue}{uos-signature-blue}',
      '\t\\setbeamercovered{transparent}',
      '}',
      '\\usepackage[english]{babel}',
      '% \\usepackage[latin1]{inputenc}',
      '\\usepackage[T1]{fontenc}',
      '\\usepackage{kotex}',
      '\\setbeamertemplate{itemize items}[circle]',
      '\\setbeamertemplate{enumerate items}[square]',
      '',
      '% \\title{Presentation Title}',
      '\\title[Short Paper Title] % (optional, use only with long paper titles)',
      '{Presentation Title}',
      '',
      '\\subtitle{Presentation Subtitle} % (optional)',
      '',
      '\\author{Choi Hyokyu}',
      '% \\author[Author, Another] % (optional, use only with lots of authors)',
      '% {F.~Author\\inst{1} \\and S.~Another\\inst{2}}',
      '',
      '\\institute[UoS]{University of Seoul}',
      '% \\institute[Universities of Somewhere and Elsewhere] % (optional, but mostly needed)',
      '% {',
      '%   \\inst{1}%',
      '%   Department of Computer Science\\\\',
      '%   University of Somewhere',
      '%   \\and',
      '%   \\inst{2}%',
      '%   Department of Theoretical Philosophy\\\\',
      '%   University of Elsewhere',
      '% }',
      '',
      '% \\date{}',
      '\\date[Short Occasion]',
      '{Date / Occasion}',
      '',
      '\\subject{Talks}',
      '',
      '\\titlegraphic{\\includegraphics[width=0.17\\textwidth]{~/Pictures/uos-emblem.png}}',
      '% \\pgfdeclareimage[height=0.5cm]{uos-logo}{~/Pictures/uos-logo.png}',
      '% \\logo{\\pgfuseimage{uos-logo}}',
      '',
      '\\AtBeginSection[]',
      '{',
      '\t\\begin{frame}<beamer>{Section}',
      '\t\t\\tableofcontents[currentsection,currentsubsection]',
      '\t\\end{frame}',
      '}',
      '',
      '% \\AtBeginSubsection[]',
      '% {',
      '%     \\begin{frame}<beamer>{Outline}',
      '%         \\tableofcontents[currentsection,currentsubsection]',
      '%     \\end{frame}',
      '% }',
      '',
      '% \\beamerdefaultoverlayspecification{<+->}',
      '',
      '\\begin{document}',
      '',
      '\\begin{frame}',
      '    \\titlepage',
      '\\end{frame}',
      '',
      '\\section*{Introduction}',
      '% \\subsection{Second Subsection}',
      '',
      '\\begin{frame}{Introduction}',
      '',
      '\\end{frame}',
      '',
      '\\section*{Result}',
      '',
      '\\begin{frame}{Result}',
      '',
      '\\end{frame}',
      '',
      '\\section*{Summary}',
      '',
      '\\begin{frame}{Summary}',
      '',
      '\\end{frame}',
      '',
      '\\section{Backup}',
      '',
      '\\begin{frame}{Backup}',
      '\\end{frame}',
      '',
      '\\end{document}'
    }),
  }),
  s({ trig = 'frame', name = 'beamer frame' }, {
    t({'\\begin{frame}{'}),
    i(1, '<Title>'),
    t({'}', '', '\t'}),
    i(2, '<Contents>'),
    t({'', '\\end{frame}', ''}),
  }),
  s({ trig = 'begin', name = 'LaTeX begin keyword' }, {
    t({'\\begin{'}),
    i(1, '<tag>'),
    t({'}', '', '\t'}),
    i(2, '<Contents>'),
    t({'', '\\end{'}),
    rep(1),
    t({'}'}),
  }),
  s({ trig = 'table', name = 'beamer simple table example' }, {
    t({
      '\\begin{table}',
      '\\begin{tabular}{| c || c | c |}',
      '\t\\hline',
      '\tNo. & Name & Age \\\\\\\\',
      '\t\\hline \\hline',
      '1 & John T & 24 \\\\\\\\',
      '2 & Norman P & 8 \\\\\\\\',
      '3 & Alex K & 14 \\\\\\\\',
      '\\hline',
      '\\end{tabular}',
      '\\caption{Name and age of students}',
      '\\end{table}',
    }),
  }),
  s({ trig = 'figure', name = 'beamer figure with caption' }, {
    t({'\\begin{figure}', '\t\\includegraphics[width=\\textwidth]{'}),
    i(1, '<image_path>'),
    t({'}', '\t\\caption{'}),
    i(2, '<Caption>'),
    t({'}', '\\end{figure}', ''}),
  }),
  s({ trig = 'image', name = 'beamer image' }, {
    t('\\includegraphics[width=\\textwidth]{'),
    i(0, '<image_path>'),
    t('}'),
  }),
  s({ trig = 'columns', name = 'beamer columns' }, {
    t({
      '\\begin{columns}',
      '',
      '\t\\begin{column}{',
    }),
    i(1, '<Column_width>'),
    t({
      '\\textwidth}',
      '\t',
    }),
    i(2, '<Contents>'),
    t({
      '\t\\end{column}',
      '',
      '\t\\begin{column}{',
    }),
    rep(1),
    t({
      '\\textwidth}',
      '\t',
    }),
    i(3, '<Contents>'),
    t({
      '}',
      '\t\\end{column}',
      '\\end{columns}',
    })
  }),
  s({ trig = 'column_line', name = 'beamer column new line'}, {
    t({'\\begin{column}{'}),
    i(1, '<Column_width>'),
    t({'\\textwidth}', ''}),
    i(2, '<Contents>'),
    t({'', '\\end{column}'}),
  }),
	s({ trig = 'itemize', name = 'beamer itemize' }, {
		t({ "\\begin{itemize}", "\t\\item " }),
		i(1),
		d(2, rec_ls, {}),
		t({ "", "\\end{itemize}" }),
	}),
	s({ trig = 'enumerate', name = 'beamer enumerate' }, {
		t({ "\\begin{enumerate}", "\t\\item " }),
		i(1),
		d(2, rec_ls, {}),
		t({ "", "\\end{enumerate}" }),
	}),
  s({ trig = 'item', name = 'beamer item for itemize or enumerate' }, {
    t('\\item '),
    i(1, '<Contents>'),
  }),
  s({ trig = 'pause', name = 'beamer pause, overlay' }, {
    t({'\\pause', ''}),
  }),
  s({ trig = 'section', name = 'beamer section' }, {
    t('\\section{'),
    i(1, '<Section Title>'),
    t({'}', ''}),
  }),
  s({ trig = 'alert', name = 'beamer alert' }, {
    t('\\alert{'),
    i(1, '<text>'),
    t('}'),
  }),
  s({ trig = 'vskip', name = 'beamer vskip' }, {
    t({'\\vskip0pt plus.5fill', ''}),
  }),
  s({ trig = 'center', name = 'beamer center' }, {
    t({'\\begin{center}', '\t'}),
    i(1, '<Contents>'),
    t({'', '\\end{center}'}),
  }),
  s({ trig = 'font_size', name = 'LaTeX change font_size in scope' }, {
    t('\\fontsize{'),
    i(1, '<size>'),
    t('pt}{'),
    i(2, '<bskip>'),
    t({'pt}\\selectfont', ''}),
  }),
  s({ trig = 'code_block', name = 'LaTeX code block' }, {
    t('\\texttt{'),
    i(1, '<codes>'),
    t('}'),
  }),
  s({ trig = 'bold', name = 'LaTeX bold font' }, {
    t('\\textbf{'),
    i(1, '<text>'),
    t('}'),
  }),
})
