require('plugin.lualine')
require('plugin.nvim-tree')
require('plugin.comment')
require('plugin.nvim-autopairs')
require('plugin.indent-blankline')
require('plugin.nvim-cmp')
require('plugin.telescope')
require('plugin.vim-python-doc')
require('plugin.lsp')
require('plugin.luasnippets')
require('plugin.yazi')
require('plugin.gitsigns')
require('plugin.codesnap')
require('plugin.image')
-- require('plugin.tagbar')
require('plugin.nvim-treesitter')
-- require('plugin.multicursor')

vim.cmd[[colorscheme tokyonight-moon]]
